// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_FIRE']!,
    appId: '1:617928126569:web:d957f193e9db7e20a332f8',
    messagingSenderId: '617928126569',
    projectId: 'find-my-pickle',
    authDomain: 'find-my-pickle.firebaseapp.com',
    storageBucket: 'find-my-pickle.firebasestorage.app',
    measurementId: 'G-Z5NT15VHPP',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['AND_FIRE']!,
    appId: '1:617928126569:android:c08acfaa12921f0ca332f8',
    messagingSenderId: '617928126569',
    projectId: 'find-my-pickle',
    storageBucket: 'find-my-pickle.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_FIRE']!,
    appId: '1:617928126569:ios:848b059d99cf3114a332f8',
    messagingSenderId: '617928126569',
    projectId: 'find-my-pickle',
    storageBucket: 'find-my-pickle.firebasestorage.app',
    iosClientId: '617928126569-384ngrab6s3pvuv3gd4ah1vgu8rajq8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.findMyPickle',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MAC_FIRE']!,
    appId: '1:617928126569:ios:848b059d99cf3114a332f8',
    messagingSenderId: '617928126569',
    projectId: 'find-my-pickle',
    storageBucket: 'find-my-pickle.firebasestorage.app',
    iosClientId: '617928126569-384ngrab6s3pvuv3gd4ah1vgu8rajq8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.findMyPickle',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['WIND_FIRE']!,
    appId: '1:617928126569:web:38b3f66523dd8939a332f8',
    messagingSenderId: '617928126569',
    projectId: 'find-my-pickle',
    authDomain: 'find-my-pickle.firebaseapp.com',
    storageBucket: 'find-my-pickle.firebasestorage.app',
    measurementId: 'G-G0ZTS11H8V',
  );
}
