// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:find_my_pickle/secrets_config/app_secrets.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return FirebaseOptions(
        apiKey: AppSecrets.webFire, // Use from AppSecrets
        appId: '1:708374722404:web:603e7719bc29d8b6e62c71',
        messagingSenderId: '708374722404',
        projectId: 'find-my-pickle-c1089',
        authDomain: 'find-my-pickle-c1089.firebaseapp.com',
        storageBucket: 'find-my-pickle-c1089.firebasestorage.app',
        measurementId: 'G-GKCWJBQ8S1',
      );
    }
    
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return FirebaseOptions(
          apiKey: AppSecrets.andFire, // Use from AppSecrets
          appId: '1:708374722404:android:1a054e53224b4ac5e62c71',
          messagingSenderId: '708374722404',
          projectId: 'find-my-pickle-c1089',
          storageBucket: 'find-my-pickle-c1089.firebasestorage.app',
        );
        
      case TargetPlatform.iOS:
        return FirebaseOptions(
          apiKey: AppSecrets.iosFire, // Use from AppSecrets
          appId: '1:708374722404:ios:44359ba96e1e03b1e62c71',
          messagingSenderId: '708374722404',
          projectId: 'find-my-pickle-c1089',
          storageBucket: 'find-my-pickle-c1089.firebasestorage.app',
          iosBundleId: 'com.example.findMyPickle',
        );
        
      case TargetPlatform.macOS:
        return FirebaseOptions(
          apiKey: AppSecrets.macFire, // Use from AppSecrets
          appId: '1:708374722404:ios:44359ba96e1e03b1e62c71',
          messagingSenderId: '708374722404',
          projectId: 'find-my-pickle-c1089',
          storageBucket: 'find-my-pickle-c1089.firebasestorage.app',
          iosBundleId: 'com.example.findMyPickle',
        );
        
      case TargetPlatform.windows:
        return FirebaseOptions(
          apiKey: AppSecrets.windFire, // Use from AppSecrets
          appId: '1:708374722404:web:a5f7a548e133f930e62c71',
          messagingSenderId: '708374722404',
          projectId: 'find-my-pickle-c1089',
          authDomain: 'find-my-pickle-c1089.firebaseapp.com',
          storageBucket: 'find-my-pickle-c1089.firebasestorage.app',
          measurementId: 'G-R5WCDXMB1L',
        );
        
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
        
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}